-- MySQL Script generated by MySQL Workbench
-- 07/31/17 04:42:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- -----------------------------------------------------
-- Schema lj_charts_db
-- -----------------------------------------------------
-- Database schema for the lj-charts web application.
DROP SCHEMA IF EXISTS `lj_charts_db` ;

-- -----------------------------------------------------
-- Schema lj_charts_db
--
-- Database schema for the lj-charts web application.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lj_charts_db` DEFAULT CHARACTER SET utf8 ;
USE `lj_charts_db` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `usr_id` INT NOT NULL,
  `usr_firstName` VARCHAR(255) NOT NULL,
  `usr_lastName` VARCHAR(255) NULL,
  `usr_username` VARCHAR(45) NOT NULL,
  `usr_email` VARCHAR(255) NOT NULL,
  `usr_role` VARCHAR(45) NOT NULL DEFAULT 'normal',
  `usr_password` VARCHAR(45) NOT NULL,
  `usr_profileImage` VARCHAR(45) NOT NULL DEFAULT 'default.png' COMMENT 'Profile picture.',
  `usr_status` VARCHAR(45) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `usr_id_UNIQUE` (`usr_id` ASC),
  UNIQUE INDEX `usr_username_UNIQUE` (`usr_username` ASC),
  UNIQUE INDEX `usr_email_UNIQUE` (`usr_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Analyte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Analyte` ;

CREATE TABLE IF NOT EXISTS `Analyte` (
  `an_id` INT NOT NULL AUTO_INCREMENT,
  `an_name` VARCHAR(255) NOT NULL COMMENT 'Name of the analyte.',
  `an_nits` VARCHAR(45) NOT NULL COMMENT 'Units of Measurement.',
  `an_HighControl` VARCHAR(255) NULL COMMENT 'High-level ControlMatrial.',
  `an_NormalControl` VARCHAR(255) NULL COMMENT 'Normal level ControlMaterial.',
  `an_LowControl` VARCHAR(255) NULL COMMENT 'Low-level ControlMaterial.',
  `User_usr_id` INT NOT NULL,
  PRIMARY KEY (`an_id`, `User_usr_id`),
  UNIQUE INDEX `id_UNIQUE` (`an_id` ASC),
  INDEX `fk_Analyte_User_idx` (`User_usr_id` ASC),
  CONSTRAINT `fk_Analyte_User`
    FOREIGN KEY (`User_usr_id`)
    REFERENCES `User` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControlMaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControlMaterial` ;

CREATE TABLE IF NOT EXISTS `ControlMaterial` (
  `cm_id` INT NOT NULL AUTO_INCREMENT,
  `cm_name` VARCHAR(255) NOT NULL COMMENT 'The name of the ControlMaterial',
  `cm_units` VARCHAR(255) NOT NULL COMMENT 'The units of measurement, inherited from the analyte.',
  `cm_LotNumber` VARCHAR(255) NULL COMMENT 'Batch number for purchased ControlMaterial.',
  `cm_level` VARCHAR(255) NULL COMMENT 'The level of control: high, normal, or low.',
  `cm_mean` DOUBLE NULL COMMENT 'The mean of the Data field.',
  `cm_sd` DOUBLE NULL COMMENT 'Standard deviation of the Data field.',
  `Data` LONGTEXT NULL COMMENT 'The list of actual run results, in order of generation/run.',
  `DataPoints` INT NULL COMMENT 'The number of runs',
  `Plus3SD` DOUBLE NULL COMMENT '(Mean)+3(Standard deviation)',
  `Plus2SD` DOUBLE NULL COMMENT '(Mean)+2(Standard deviation)',
  `Plus1SD` DOUBLE NULL COMMENT '(Mean)+1(Standard deviation)',
  `Minus1SD` DOUBLE NULL COMMENT '(Mean)-1(Standard deviation)',
  `Minus2SD` DOUBLE NULL COMMENT '(Mean)-2(Standard deviation)',
  `Minus3SD` DOUBLE NULL COMMENT '(Mean)-3(Standard deviation)',
  `cm_status` VARCHAR(45) NULL DEFAULT 'okay',
  `User_usr_id` INT NOT NULL,
  `Analyte_an_id` INT NOT NULL,
  `Analyte_User_usr_id` INT NOT NULL,
  PRIMARY KEY (`cm_id`, `User_usr_id`, `Analyte_an_id`, `Analyte_User_usr_id`),
  UNIQUE INDEX `id_UNIQUE` (`cm_id` ASC),
  INDEX `fk_ControlMaterial_User1_idx` (`User_usr_id` ASC),
  INDEX `fk_ControlMaterial_Analyte1_idx` (`Analyte_an_id` ASC, `Analyte_User_usr_id` ASC),
  CONSTRAINT `fk_ControlMaterial_User1`
    FOREIGN KEY (`User_usr_id`)
    REFERENCES `User` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ControlMaterial_Analyte1`
    FOREIGN KEY (`Analyte_an_id` , `Analyte_User_usr_id`)
    REFERENCES `Analyte` (`an_id` , `User_usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControlMaterialResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControlMaterialResult` ;

CREATE TABLE IF NOT EXISTS `ControlMaterialResult` (
  `cmr_id` INT NOT NULL,
  `cmr_time` DATETIME DEFAULT NULL COMMENT 'The server time on submission.\n',
  `cmr_value` DOUBLE NOT NULL COMMENT 'The value of a run.',
  `cmr_instrument` VARCHAR(255) NULL COMMENT 'The instrument/machine used.',
  `cmr_assayMethod` VARCHAR(255) NULL,
  `cmr_temperature` DOUBLE NULL,
  `ControlMaterial_cm_id` INT NOT NULL,
  `ControlMaterial_User_usr_id` INT NOT NULL,
  `ControlMaterial_Analyte_an_id` INT NOT NULL,
  `ControlMaterial_Analyte_User_usr_id` INT NOT NULL,
  `User_usr_id` INT NOT NULL,
  PRIMARY KEY (`cmr_id`, `ControlMaterial_cm_id`, `ControlMaterial_User_usr_id`, `ControlMaterial_Analyte_an_id`, `ControlMaterial_Analyte_User_usr_id`, `User_usr_id`),
  UNIQUE INDEX `id_UNIQUE` (`cmr_id` ASC),
  INDEX `fk_ControlMaterialResult_ControlMaterial1_idx` (`ControlMaterial_cm_id` ASC, `ControlMaterial_User_usr_id` ASC, `ControlMaterial_Analyte_an_id` ASC, `ControlMaterial_Analyte_User_usr_id` ASC),
  INDEX `fk_ControlMaterialResult_User1_idx` (`User_usr_id` ASC),
  CONSTRAINT `fk_ControlMaterialResult_ControlMaterial1`
    FOREIGN KEY (`ControlMaterial_cm_id` , `ControlMaterial_User_usr_id` , `ControlMaterial_Analyte_an_id` , `ControlMaterial_Analyte_User_usr_id`)
    REFERENCES `ControlMaterial` (`cm_id` , `User_usr_id` , `Analyte_an_id` , `Analyte_User_usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ControlMaterialResult_User1`
    FOREIGN KEY (`User_usr_id`)
    REFERENCES `User` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
